### PR TITLE
Fix a crash in ibus-table caused by "src/ibusenginesimple: Do not upd…

### PR DESCRIPTION
**Pull request by mike-fabian**
…ate zero length preedit text"

This causes a crash when typing for example Backspace or Down with an empty preedit in ibus-table:

commit 7bfd2ad82014bdaffb39e59c166d1d7c507e4ee7 (HEAD -> simple-hide-0-preedit, fujiwarat/simple-hide-0-preedit)
Author: fujiwarat <takao.fujiwara1@gmail.com>
Date:   Thu Sep 14 17:44:26 2023 +0900

    src/ibusenginesimple: Do not update zero length preedit text

    Several engines can inherit IBusEngieSimple for the compose key support
    likes Anthy, Hangul, M17n and it could have the duplicated preedit text
    between the engine and the parent IBusEngineSimple and it could update
    the preedit text mutually by mistake.

    Then the preedit text should not be hidden for zero length at least.
    This update might not be enough but hope to fix the cursor position
    reset with hiding the preedit text against the reported issue with
    `m17n:sa:itrans` engine.

    BUG=https://github.com/ibus/ibus/issues/2536

### CODE REVIEW

**Comment by mike-fabian** [comment]
Video showing the problem.

In the terminal a `pgrep -a -f table` is running every second, showing the ibus-table process if it exists. 

Switch to ibus-table cangjie5 using Super+space. The floating panel for ibus-table is shown and the process is seen in the terminal.

Type `Backspace` into gedit.

The floating panel disappears and the ibus-table process disappears.

https://github.com/fujiwarat/ibus/assets/2330175/74e734d2-77e4-4c94-882b-decf49739b20

**Comment by itt533** [comment]
it's been quite some time that this has been reported. Is there any hope to see something soon?

**Comment by fujiwarat** [comment]
I thnk `priv->updated_preedit == NULL` should not happen and your engine has a problem.

**Comment by mike-fabian** [comment]
> I thnk `priv->updated_preedit == NULL` should not happen and your engine has a problem.

I think even if the engine has such a problem, it should not crash. 

What could ibus-table be doing wrong to cause that problem?

**Comment by fujiwarat** [comment]
> What could ibus-table be doing wrong to cause that problem?

I guess your engine didn't call IBus.init() or failed some initializations in ibus_enigne_simple_init().
I updated https://github.com/ibus/ibus/pull/2566 to move the initialized simple->priv->updated_preedit line more earlier than the initialized compose table lines in ibus_engine_simple_init().

**Pull request closed without merging**
